### ISSUE TITLE
TODO for nnue.md

### ISSUE THREAD

**Issue by Sopel97** [glinscott/nnue-pytorch#127]
- [ ] info about LR scheduling
- [ ] info about optimizers
- [ ] some results regarding net size (https://docs.google.com/document/d/1gTlrr02qSNKiXNZ_SuO4-RjK4MXBiFlLE6jvNqqMkAY/edit#heading=h.p7t1qfux64dc exps 84, 85, 86, 89)
- [ ] about data used to train the nets (filtering, mirroring and stuff)
- [ ] fix header links in doc
- [ ] make headings understandable without context
- [ ] consistent formatting (for feature set names, net arch names, etc...)
- [ ] backprop math
